import '../models/event_model.dart';
import '../models/session_model.dart';
import '../models/speaker_model.dart';
import '../models/user_model.dart';

class DataService {
  // Demo user for local auth
  static const demoUser = UserModel(
    id: 'user_001',
    email: 'demo@apscvir.org',
    nameEn: 'Dr. Alistair Thorne',
    nameZh: '艾利斯泰尔·索恩博士',
    titleEn: 'Senior Oncology Curator',
    titleZh: '高级肿瘤学研究员',
    organizationEn: "ST. JUDE'S MEDICAL RESEARCH CENTER",
    organizationZh: '圣裘德医学研究中心',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop',
    role: UserRole.vip,
  );

  static final List<EventModel> events = [
    EventModel(
      id: 'evt_001',
      titleEn: 'Global Oncology Summit 2026',
      titleZh: '2026 全球肿瘤学创新峰会',
      descriptionEn: 'The premier global conference on oncology innovations and breakthroughs.',
      descriptionZh: '全球顶级肿瘤学创新与突破学术会议。',
      locationEn: 'Convention Center, San Francisco, CA',
      locationZh: '旧金山国际会议中心, CA',
      imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop',
      startDate: DateTime(2026, 10, 15),
      endDate: DateTime(2026, 10, 17),
      organizerEn: 'APSCVIR',
      organizerZh: 'APSCVIR',
      tags: ['Oncology', 'Innovation'],
      currentAttendees: 248,
      maxAttendees: 500,
    ),
    EventModel(
      id: 'evt_002',
      titleEn: 'Future of Digital Healthcare & AI Forum',
      titleZh: '未来数字医疗与AI论坛',
      descriptionEn: 'Exploring the intersection of AI, digital health, and clinical practice.',
      descriptionZh: '探讨AI、数字健康与临床实践的交叉前沿。',
      locationEn: 'Grand Hyatt, Shanghai, CN',
      locationZh: '上海君悦大酒店, CN',
      imageUrl: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?q=80&w=2070&auto=format&fit=crop',
      startDate: DateTime(2026, 11, 2),
      endDate: DateTime(2026, 11, 4),
      organizerEn: 'APSCVIR & Digital Health Alliance',
      organizerZh: 'APSCVIR & 数字健康联盟',
      tags: ['Digital Health', 'AI'],
      isFeatured: true,
      currentAttendees: 180,
      maxAttendees: 300,
    ),
    EventModel(
      id: 'evt_003',
      titleEn: 'International Cardiovascular Expo',
      titleZh: '国际心血管医学博览会',
      descriptionEn: 'Annual expo showcasing latest cardiovascular research and technology.',
      descriptionZh: '年度心血管研究与技术展览博览会。',
      locationEn: 'Exhibition Hall, Berlin, DE',
      locationZh: '柏林展览中心, DE',
      imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop',
      startDate: DateTime(2026, 12, 12),
      endDate: DateTime(2026, 12, 12),
      organizerEn: 'European Cardiovascular Society',
      organizerZh: '欧洲心血管学会',
      tags: ['Cardiovascular', 'Technology'],
      currentAttendees: 95,
      maxAttendees: 100,
    ),
  ];

  static final List<SpeakerModel> speakers = [
    const SpeakerModel(
      id: 'spk_001',
      nameEn: 'Dr. Sarah Chen, PhD',
      nameZh: 'Sarah Chen 博士',
      titleEn: 'Director of Bio-Informatics',
      titleZh: '生物信息学主任',
      organizationEn: 'Stanford Medicine',
      organizationZh: '斯坦福医学院',
      bioEn: 'Pioneer in computational genomics with 20+ years of research experience.',
      bioZh: '计算基因组学先驱，拥有20余年研究经验。',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop',
      category: SpeakerCategory.keynote,
    ),
    const SpeakerModel(
      id: 'spk_002',
      nameEn: 'Dr. Alistair Thorne',
      nameZh: 'Alistair Thorne 博士',
      titleEn: 'Senior Oncology Curator',
      titleZh: '资深肿瘤学研究员',
      organizationEn: "St. Jude's Medical Research Center",
      organizationZh: '圣裘德医学研究中心',
      bioEn: 'Leading expert in targeted cancer therapies and clinical trials.',
      bioZh: '靶向癌症疗法与临床试验的领先专家。',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop',
      category: SpeakerCategory.vipGuest,
    ),
    const SpeakerModel(
      id: 'spk_003',
      nameEn: 'Prof. James Sterling',
      nameZh: 'James Sterling 教授',
      titleEn: 'Oncology Lead',
      titleZh: '肿瘤学负责人',
      organizationEn: 'Mayo Clinic',
      organizationZh: '梅奥诊所',
      bioEn: 'Renowned oncologist specializing in CAR-T cell therapy breakthroughs.',
      bioZh: 'CAR-T细胞疗法领域的知名肿瘤学家。',
      avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=200&auto=format&fit=crop',
      category: SpeakerCategory.research,
    ),
    const SpeakerModel(
      id: 'spk_004',
      nameEn: 'Dr. Elena Rodriguez',
      nameZh: 'Elena Rodriguez 博士',
      titleEn: 'Senior Pharmacologist',
      titleZh: '高级药理学家',
      organizationEn: 'Novartis',
      organizationZh: '诺华制药',
      bioEn: 'Expert in precision medicine and drug dosage optimization.',
      bioZh: '精准医学与药物剂量优化专家。',
      avatarUrl: 'https://images.unsplash.com/photo-1594824461559-67d483b3e32e?q=80&w=200&auto=format&fit=crop',
      category: SpeakerCategory.workshop,
    ),
  ];

  static List<SessionModel> getSessions(String eventId) {
    // Sessions for evt_001 (Global Oncology Summit)
    if (eventId == 'evt_001') {
      return [
        // Day 0 (Oct 15)
        SessionModel(
          id: 'ses_001', eventId: eventId,
          titleEn: 'Future of AI in Genomic Research',
          titleZh: '人工智能在基因组研究中的未来展望',
          roomEn: 'Lecture Hall 1', roomZh: '第一学术报告厅',
          startTime: DateTime(2026, 10, 15, 9, 0),
          endTime: DateTime(2026, 10, 15, 10, 0),
          type: SessionType.keynote,
          speakerId: 'spk_001', speakerName: 'Dr. Sarah Chen, PhD',
          speakerTitleEn: 'Director of Bio-Informatics, Stanford Medicine',
          speakerTitleZh: '斯坦福医学院生物信息学主任',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop',
          dayIndex: 0,
        ),
        SessionModel(
          id: 'ses_002', eventId: eventId,
          titleEn: 'Breakthroughs in CAR-T Cell Therapy',
          titleZh: 'CAR-T细胞疗法的重大突破',
          roomEn: 'Seminar Hall 2', roomZh: '研讨会第二厅',
          startTime: DateTime(2026, 10, 15, 10, 15),
          endTime: DateTime(2026, 10, 15, 11, 15),
          type: SessionType.researchPaper,
          speakerId: 'spk_003', speakerName: 'Prof. James Sterling',
          speakerTitleEn: 'Oncology Lead, Mayo Clinic',
          speakerTitleZh: '梅奥诊所肿瘤学负责人',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=200&auto=format&fit=crop',
          dayIndex: 0,
        ),
        SessionModel(
          id: 'ses_003', eventId: eventId,
          titleEn: 'Precision Medicine: From Data to Dosage',
          titleZh: '精准医学：从数据到剂量',
          roomEn: 'Innovation Lab 4', roomZh: '创新实验室 4',
          startTime: DateTime(2026, 10, 15, 13, 0),
          endTime: DateTime(2026, 10, 15, 14, 30),
          type: SessionType.workshop,
          speakerId: 'spk_004', speakerName: 'Dr. Elena Rodriguez',
          speakerTitleEn: 'Senior Pharmacologist, Novartis',
          speakerTitleZh: '诺华高级药理学家',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1594824461559-67d483b3e32e?q=80&w=200&auto=format&fit=crop',
          dayIndex: 0,
        ),
        SessionModel(
          id: 'ses_004', eventId: eventId,
          titleEn: 'Ethical Frameworks for Global Health Data',
          titleZh: '全球健康数据的伦理框架',
          roomEn: 'Digital Suite A', roomZh: '数字套房 A',
          startTime: DateTime(2026, 10, 15, 15, 0),
          endTime: DateTime(2026, 10, 15, 16, 30),
          type: SessionType.panel,
          speakerName: 'Panel: WHO Ethics Committee',
          speakerTitleEn: 'Multi-speaker Session',
          speakerTitleZh: '多讲者联合论坛',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1537368910025-7028a1ab9b98?q=80&w=200&auto=format&fit=crop',
          dayIndex: 0,
        ),
        // Day 1 (Oct 16)
        SessionModel(
          id: 'ses_005', eventId: eventId,
          titleEn: 'Precision Medicine & AI Diagnostics',
          titleZh: '精准医疗与AI诊断',
          roomEn: 'Lecture Hall 1', roomZh: '第一学术报告厅',
          startTime: DateTime(2026, 10, 16, 9, 0),
          endTime: DateTime(2026, 10, 16, 10, 30),
          type: SessionType.keynote,
          speakerName: 'Dr. Aris Thorne',
          speakerTitleEn: 'Senior Oncology Researcher',
          speakerTitleZh: '高级肿瘤学研究员',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop',
          dayIndex: 1,
        ),
        SessionModel(
          id: 'ses_006', eventId: eventId,
          titleEn: 'Targeted Immunotherapy Workshop',
          titleZh: '新型靶向免疫疗法临床研讨',
          roomEn: 'Lab Center', roomZh: '实验教学中心',
          startTime: DateTime(2026, 10, 16, 11, 0),
          endTime: DateTime(2026, 10, 16, 12, 30),
          type: SessionType.workshop,
          speakerName: 'Elena Rodriguez, MD',
          speakerTitleEn: 'Senior Pharmacologist',
          speakerTitleZh: '高级药理学家',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
          dayIndex: 1,
        ),
        SessionModel(
          id: 'ses_007', eventId: eventId,
          titleEn: 'Genomic Data in Rare Diseases',
          titleZh: '基因组学数据在罕见病中的应用',
          roomEn: 'Medical Data Lab', roomZh: '医学数据实验室',
          startTime: DateTime(2026, 10, 16, 14, 15),
          endTime: DateTime(2026, 10, 16, 15, 45),
          type: SessionType.researchPaper,
          speakerName: 'Prof. Marcus Chen',
          speakerTitleEn: 'Genomics Researcher',
          speakerTitleZh: '基因组学研究员',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop',
          dayIndex: 1,
        ),
        // Day 2 (Oct 17)
        SessionModel(
          id: 'ses_008', eventId: eventId,
          titleEn: 'Next-Generation Sequencing in Oncology',
          titleZh: '新一代基因组测序在肿瘤学中的应用',
          roomEn: 'Lecture Hall 1', roomZh: '第一学术报告厅',
          startTime: DateTime(2026, 10, 17, 9, 0),
          endTime: DateTime(2026, 10, 17, 10, 30),
          type: SessionType.keynote,
          speakerId: 'spk_001', speakerName: 'Dr. Sarah Chen, PhD',
          speakerTitleEn: 'Director of Bio-Informatics',
          speakerTitleZh: '生物信息学主任',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=200&auto=format&fit=crop',
          dayIndex: 2,
        ),
        SessionModel(
          id: 'ses_009', eventId: eventId,
          titleEn: 'Closing Ceremony & Awards',
          titleZh: '闭幕式及颁奖典礼',
          roomEn: 'Grand Ballroom', roomZh: '宴会大厅',
          startTime: DateTime(2026, 10, 17, 15, 0),
          endTime: DateTime(2026, 10, 17, 17, 0),
          type: SessionType.panel,
          speakerName: 'Organizing Committee',
          speakerTitleEn: 'APSCVIR 2026',
          speakerTitleZh: 'APSCVIR 2026',
          speakerAvatarUrl: 'https://images.unsplash.com/photo-1537368910025-7028a1ab9b98?q=80&w=200&auto=format&fit=crop',
          dayIndex: 2,
        ),
      ];
    }
    return [];
  }
}
